### ISSUE TITLE
[+] Tracking Broken Binaries

### ISSUE THREAD

**Issue by Azathothas** [leleliu008/ndk-pkg-formula-repository-official-core#10]
This issue should serve as tracker for tracking binaries that don't work despite being promoted/included in the [./formula](https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/tree/master/formula) dir.

This issue should also track a list of binaries that won't work if built statically (`--fsle`) due to the following reasons:
> - https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/tree/master/build_script#dns-issues
> - https://github.com/termux/termux-packages/wiki/Common-porting-problems

Perhaps this can be later added to the readme to warn people or the formulae itself could be modified to not support `--fsle`.

The list will be based on prebuilt binaries from:
> - https://github.com/fpliu1214/uppm-package-repository-android-aarch64/releases/latest
> - My own buildscripts from https://github.com/Azathothas/Toolpacks/tree/main/.github/scripts/arm64_v8a_Android/bins

This comment will be edited based on fixes & solutions suggested.

---
- Broken Binaries
> - [aria2](https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/aria2.yml) : https://github.com/fpliu1214/uppm-package-repository-android-aarch64/releases/download/2024.04.29/aria2-1.37.0-android-aarch64.tar.xz
> > ```bash
> > ❯ aria2c --help
> > !# Static Built
> > Exception caught
> > Exception: [/home/runner/.ndk-pkg/run/2303/android-34-arm64-v8a/aria2/src/src/Platform.cc:125] errorCode=1 OSSL_PROVIDER_load 'legacy' failed.
> > 
> > !# Dynamic Built android-29-arm64-v8a
> >CANNOT LINK EXECUTABLE "./aria2c": library "libaria2.so" not found: needed by main executable
> > ```
> - [util-linux](https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/util-linux.yml) : https://github.com/fpliu1214/uppm-package-repository-android-aarch64/releases/download/2024.04.29/util-linux-2.39.3-android-aarch64.tar.xz
> > ```bash
> > !# It seems due to `--disable-all-programs` configure flag, the entire build process produces no binaries in /bin or /sbin
> > ```
> - [tmux](https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/tmux.yml) : https://github.com/fpliu1214/uppm-package-repository-android-aarch64/releases/download/2024.04.29/tmux-3.4-android-aarch64.tar.xz
> > ```bash
> > !# Both static / dynamic build exit with the same error
> > can't find terminfo database
> > 
> >  !# I found this: https://github.com/tmux/tmux/issues/743 , but no solution worked
> > ```
---
- Dynamic Only (Static Bin Will Not Work)
> - [axel](https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/axel.yml) : https://github.com/fpliu1214/uppm-package-repository-android-aarch64/releases/download/2024.04.29/axel-2.17.14-android-aarch64.tar.xz
> > - https://github.com/axel-download-accelerator/axel/issues/438
> > ```bash
> > Unable to connect to server github.com:443: No address associated with hostname
> > (null)
> > 
> > !# Dynamic Built android-29-arm64-v8a has certs issues but works with -k | --insecure flag
> > SSL error: (null)
> >(null)
> > !# This is fixed by using SSL_CERT_FILE env variable as stated in the readme
> >```

**Comment by leleliu008** [comment]
> ```shell
> !# Dynamic Built android-29-arm64-v8a
> CANNOT LINK EXECUTABLE "./aria2c": library "libaria2.so" not found: needed by main executable
> ```

This is a bug, It will be fixed in next release.

**Comment by leleliu008** [comment]
> ```shell
> !# Both static / dynamic build exit with the same error
> can't find terminfo database
> ```

run tmux on termux, you could do this:

```bash
export TMUX_TMPDIR="$HOME/tmux-tmp-dir"
ln -s /data/data/com.termux/files/home/../usr/lib/terminfo ~/.terminfo
```

**Comment by leleliu008** [comment]
> ```shell
> !# It seems due to `--disable-all-programs` configure flag, the entire build process produces no binaries in /bin or /sbin
> ```

I split util-linux to several sub packages e.g. libuuid, getopt, etc

**Comment by Azathothas** [comment]
The aria2c dynamic build works perfectly, but the static built has dns issues like always:
```bash
❯ ./aria2c-static https://bin.ajam.dev/arm64_v8a_Android/tailscale

05/17 11:40:17 [NOTICE] Downloading 1 item(s)

05/17 11:40:17 [ERROR] CUID#7 - Download aborted. URI=https://bin.ajam.dev/arm64_v8a_Android/tailscale
Exception: [/root/.ndk-pkg/run/225417/android-34-arm64-v8a/aria2/src/src/AbstractCommand.cc:351] errorCode=19 URI=https://bin.ajam.dev/arm64_v8a_Android/tailscale
  -> [/root/.ndk-pkg/run/225417/android-34-arm64-v8a/aria2/src/src/NameResolver.cc:60] errorCode=19 Failed to resolve the hostname bin.ajam.dev, cause: No address associated with hostname

05/17 11:40:17 [NOTICE] Download GID#d7714c172a344d74 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
d7714c|ERR |        n/a|https://bin.ajam.dev/arm64_v8a_Android/tailscale

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
```

> run tmux on termux, you could do this:
```bash
export TMUX_TMPDIR="$HOME/tmux-tmp-dir"
ln -s ~/../usr/lib/terminfo ~/.terminfo
```

That still doesn't work, I now get
```bash
no suitable socket path
```

> I split util-linux to several sub packages e.g. libuuid, getopt, etc

I can only find:
https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/libuuid.yml
https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/getopt.yml

Are these missing?
```bash
addpart
agetty
blkdiscard
blkid
blkpr
blkzone
blockdev
cal
cfdisk
chcpu
chfn
chmem
choom
chrt
chsh
col
colcrt
colrm
column
ctrlaltdel
delpart
dmesg
eject
fadvise
fallocate
fdisk
fincore
findfs
findmnt
flock
fsck
fsck.cramfs
fsck.minix
fsfreeze
fstrim
hardlink
hexdump
hwclock
i386
ionice
ipcmk
ipcrm
ipcs
irqtop
isosize
kill
last
lastb
ldattach
linux32
linux64
logger
login
look
losetup
lsblk
lscpu
lsfd
lsipc
lsirq
lslocks
lslogins
lsmem
lsns
mcookie
mesg
mkfs
mkfs.bfs
mkfs.cramfs
mkfs.minix
mkswap
more
mount
mountpoint
namei
nologin
nsenter
partx
pipesz
pivot_root
prlimit
readprofile
rename
renice
resizepart
rev
rfkill
rtcwake
runuser
script
scriptlive
scriptreplay
setarch
setpriv
setsid
setterm
sfdisk
sulogin
swaplabel
swapoff
swapon
switch_root
taskset
uclampset
ul
umount
uname26
unshare
utmpdump
uuidd
uuidgen
uuidparse
waitpid
wall
wdctl
whereis
wipefs
write
x86_64
zramctl
```

**Comment by leleliu008** [comment]
> > ```shell
> > !# Dynamic Built android-29-arm64-v8a
> > CANNOT LINK EXECUTABLE "./aria2c": library "libaria2.so" not found: needed by main executable
> > ```
> 
> This is a bug, It will be fixed in next release.

This has been fixed.

**Comment by leleliu008** [comment]
> > run tmux on termux, you could do this:
> 
> ```shell
> export TMUX_TMPDIR="$HOME/tmux-tmp-dir"
> ln -s ~/../usr/lib/terminfo ~/.terminfo
> ```
> 
> That still doesn't work, I now get
> 
> ```shell
> no suitable socket path
> ```

```shell
export TMUX_TMPDIR="$HOME/tmux-tmp-dir"
install -d "$TMUX_TMPDIR"
 ln -s ~/../usr/lib/terminfo ~/.terminfo
 ```

you should create `TMUX_TMPDIR` manully.

**Comment by Azathothas** [comment]
> ```shell
> export TMUX_TMPDIR="$HOME/tmux-tmp-dir"
> install -d "$TMUX_TMPDIR"
>  ln -s ~/../usr/lib/terminfo ~/.terminfo
> ```

Ah yes it works now, thank you!

**Comment by leleliu008** [comment]
> can only find: https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/libuuid.yml https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/getopt.yml
> 
> Are these missing?
> 
> ```shell
> addpart
> agetty
> blkdiscard
> blkid
> blkpr
> blkzone
> blockdev
> cal
> cfdisk
> chcpu
> chfn
> chmem
> choom
> chrt
> chsh
> col
> colcrt
> colrm
> column
> ctrlaltdel
> delpart
> dmesg
> eject
> fadvise
> fallocate
> fdisk
> fincore
> findfs
> findmnt
> flock
> fsck
> fsck.cramfs
> fsck.minix
> fsfreeze
> fstrim
> hardlink
> hexdump
> hwclock
> i386
> ionice
> ipcmk
> ipcrm
> ipcs
> irqtop
> isosize
> kill
> last
> lastb
> ldattach
> linux32
> linux64
> logger
> login
> look
> losetup
> lsblk
> lscpu
> lsfd
> lsipc
> lsirq
> lslocks
> lslogins
> lsmem
> lsns
> mcookie
> mesg
> mkfs
> mkfs.bfs
> mkfs.cramfs
> mkfs.minix
> mkswap
> more
> mount
> mountpoint
> namei
> nologin
> nsenter
> partx
> pipesz
> pivot_root
> prlimit
> readprofile
> rename
> renice
> resizepart
> rev
> rfkill
> rtcwake
> runuser
> script
> scriptlive
> scriptreplay
> setarch
> setpriv
> setsid
> setterm
> sfdisk
> sulogin
> swaplabel
> swapoff
> swapon
> switch_root
> taskset
> uclampset
> ul
> umount
> uname26
> unshare
> utmpdump
> uuidd
> uuidgen
> uuidparse
> waitpid
> wall
> wdctl
> whereis
> wipefs
> write
> x86_64
> zramctl
> ```

only libuuid and getopt sub package is available at this moment.  I will patch util-linux later.

**Comment by Azathothas** [comment]
It would be nice to add comments in the formula.yaml and detail what needs to be done to get them working.

Putting all these in the readme is another option but that would clutter it very quickly.

**Comment by leleliu008** [comment]
> It would be nice to add comments in the formula.yaml and detail what needs to be done to get them working.

I will add a new mapping called `cavates:`, this message will be displayed when usr run `ndk-pkg info-available` and `ndk-pkg install`

**Comment by Azathothas** [comment]
and for the binaries if they can work statically etc or not, maybe something like this as an additional field in the formula.yaml

| KEY | required? | overview |
|---- |------------ | ----------|
| be_static | optional | Value `true` OR `false` (or even yes OR No), shows if a pkg can be built statically + works (after testing) |

**Comment by leleliu008** [comment]
`pkgtype: pie` will do the trick.

**Comment by leleliu008** [comment]
`static-pie` is not considered right now.

**Comment by leleliu008** [comment]
I only consider traditional static right now. static-pie would be tested later.

**Comment by Azathothas** [comment]
I meant as a sort of future proofing, as the pkgtype serves entirely different purpose

Is it possible to have arbitrary foo:bar entries in the formula.yaml?
Would non existing keys break ndk or they would be silently ignored...

I tried to fork this repo to test but alas, Github seems to allow only one fork..

**Comment by leleliu008** [comment]
`Would non existing keys break ndk` ?

`Would non existing keys break ndk-pkg`

**Comment by leleliu008** [comment]
unrecognized keys would be ignored, it would not break ndk-pkg.

**Comment by Azathothas** [comment]
> > Is it possible to have arbitrary foo:bar entries in the formula.yaml? Would non existing keys break ndk or they would be silently ignored...
> 
> I can't quite catch this. a bit more clear?

I meant can I add additional entries in formula.yaml which aren't real keys supported by ndk-pkg

can I do this
```yaml
summary: Run your GitHub Actions locally
git-url: https://github.com/nektos/act
src-url: https://github.com/nektos/act/archive/refs/tags/v0.2.62.tar.gz
src-sha: 2b0231d02d57d5edbcc070b7c4802acf16110a0582ffb40181aaa695f2b7bf5c
license: MIT
install: gow -X main.version="$PACKAGE_VERSION" -o act main.go
```

```yaml
summary: Run your GitHub Actions locally
git-url: https://github.com/nektos/act
src-url: https://github.com/nektos/act/archive/refs/tags/v0.2.62.tar.gz
src-sha: 2b0231d02d57d5edbcc070b7c4802acf16110a0582ffb40181aaa695f2b7bf5c
license: MIT
install: gow -X main.version="$PACKAGE_VERSION" -o act main.go
foo: bar #This doesn't actually exist
```

**Comment by leleliu008** [comment]
<img width="1071" alt="Screenshot 2024-05-17 at 18 15 19" src="https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/assets/3040852/db3e92a7-f4ea-4e93-9e64-5038b763e9a7">

**Comment by leleliu008** [comment]
`curl` `wget` `aria2` are built with `libcares`, so fully statically linked executables  can use specified DNS servers. I also add the caveats for these formula.

<img width="1687" alt="Screenshot 2024-06-10 at 15 01 54" src="https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/assets/3040852/a61ae6ef-1235-4e78-a19f-51be5078c938">
<img width="1920" alt="Screenshot 2024-06-10 at 15 02 27" src="https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/assets/3040852/37f2f1be-9d60-4f15-a70e-577e70e9a6b4">
<img width="1920" alt="Screenshot 2024-06-10 at 15 02 47" src="https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/assets/3040852/f8de4a86-c092-4ccc-bf96-e81372845798">
