### ISSUE TITLE
Bash isn't complied as a Position Independent Executable, rendering the binary unlaunchable on android 5.0 and above.

### ISSUE THREAD

**Issue by ghost** [leleliu008/ndk-pkg-formula-repository-official-core#5]

**Comment by kubast2** [comment]
Just adding 'package set ccflags "-fPIE"' doesn't really work.

**Comment by kubast2** [comment]
I test out my target shell script with a toybox shell.
Thanks for looking into it.
I believe it has worked out for me in the end.
